"""Task model add category_id

Revision ID: 0a1e795a9da1
Revises: be909a720116
Create Date: 2025-12-10 18:41:15.427691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1e795a9da1'
down_revision: Union[str, None] = 'be909a720116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'category', ['category_id'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'category_id')
    # ### end Alembic commands ###
