"""Priority and DueDate columns added

Revision ID: 539d2703e0f1
Revises: 4655e8cf8eee
Create Date: 2025-12-14 22:54:22.589876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539d2703e0f1'
down_revision: Union[str, None] = '4655e8cf8eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_google_tokens_user_id', table_name='user_google_tokens')
    op.drop_table('user_google_tokens')
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('google_task_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('google_tasklist_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('synced_with_google_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_google_task_id'), 'tasks', ['google_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_google_task_id'), table_name='tasks')
    op.drop_column('tasks', 'synced_with_google_at')
    op.drop_column('tasks', 'google_tasklist_id')
    op.drop_column('tasks', 'google_task_id')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    op.create_table('user_google_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name='user_google_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_google_tokens_pkey'),
    sa.UniqueConstraint('user_id', name='user_google_tokens_user_id_key')
    )
    op.create_index('ix_user_google_tokens_user_id', 'user_google_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
