"""create_user_google_tokens_table

Revision ID: 8a4d357853bb
Revises: 0b68094e0104
Create Date: 2025-12-13 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID  # Добавьте этот импорт!

# revision identifiers, used by Alembic.
revision = '8a4d357853bb'
down_revision = '0b68094e0104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_google_tokens',
        sa.Column('id', UUID(), nullable=False),  # Теперь UUID будет определен
        sa.Column('user_id', UUID(), nullable=False),
        sa.Column('token_data', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
        sa.UniqueConstraint('user_id')
    )

    # Создаем индекс
    op.create_index('ix_user_google_tokens_user_id', 'user_google_tokens', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_google_tokens_user_id', table_name='user_google_tokens')
    op.drop_table('user_google_tokens')
    # ### end Alembic commands ###