"""Task model add user_id relation

Revision ID: bce81662842b
Revises: 0a1e795a9da1
Create Date: 2025-12-10 18:51:59.008258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce81662842b'
down_revision: Union[str, None] = '0a1e795a9da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
