"""Merge CRUD and models

Revision ID: be909a720116
Revises: fa8fcaf9ff48
Create Date: 2025-12-10 18:28:27.109488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be909a720116'
down_revision: Union[str, None] = 'fa8fcaf9ff48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.create_table('tasks')
    op.add_column('tasks', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'id')
    # ### end Alembic commands ###
